/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as ReposicaoRouteImport } from './routes/reposicao'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BalcaoRouteImport } from './routes/balcao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposicaoRoute = ReposicaoRouteImport.update({
  id: '/reposicao',
  path: '/reposicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BalcaoRoute = BalcaoRouteImport.update({
  id: '/balcao',
  path: '/balcao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balcao': typeof BalcaoRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/kits': typeof KitsRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/produtos': typeof ProdutosRoute
  '/reports': typeof ReportsRoute
  '/reposicao': typeof ReposicaoRoute
  '/suppliers': typeof SuppliersRoute
  '/vendas': typeof VendasRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balcao': typeof BalcaoRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/kits': typeof KitsRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/produtos': typeof ProdutosRoute
  '/reports': typeof ReportsRoute
  '/reposicao': typeof ReposicaoRoute
  '/suppliers': typeof SuppliersRoute
  '/vendas': typeof VendasRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balcao': typeof BalcaoRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/kits': typeof KitsRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/produtos': typeof ProdutosRoute
  '/reports': typeof ReportsRoute
  '/reposicao': typeof ReposicaoRoute
  '/suppliers': typeof SuppliersRoute
  '/vendas': typeof VendasRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/balcao'
    | '/categories'
    | '/checkout'
    | '/clientes'
    | '/compras'
    | '/dashboard'
    | '/financeiro'
    | '/insights'
    | '/kits'
    | '/movimentacoes'
    | '/produtos'
    | '/reports'
    | '/reposicao'
    | '/suppliers'
    | '/vendas'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/balcao'
    | '/categories'
    | '/checkout'
    | '/clientes'
    | '/compras'
    | '/dashboard'
    | '/financeiro'
    | '/insights'
    | '/kits'
    | '/movimentacoes'
    | '/produtos'
    | '/reports'
    | '/reposicao'
    | '/suppliers'
    | '/vendas'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/balcao'
    | '/categories'
    | '/checkout'
    | '/clientes'
    | '/compras'
    | '/dashboard'
    | '/financeiro'
    | '/insights'
    | '/kits'
    | '/movimentacoes'
    | '/produtos'
    | '/reports'
    | '/reposicao'
    | '/suppliers'
    | '/vendas'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BalcaoRoute: typeof BalcaoRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  DashboardRoute: typeof DashboardRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InsightsRoute: typeof InsightsRoute
  KitsRoute: typeof KitsRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  ProdutosRoute: typeof ProdutosRoute
  ReportsRoute: typeof ReportsRoute
  ReposicaoRoute: typeof ReposicaoRoute
  SuppliersRoute: typeof SuppliersRoute
  VendasRoute: typeof VendasRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reposicao': {
      id: '/reposicao'
      path: '/reposicao'
      fullPath: '/reposicao'
      preLoaderRoute: typeof ReposicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balcao': {
      id: '/balcao'
      path: '/balcao'
      fullPath: '/balcao'
      preLoaderRoute: typeof BalcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BalcaoRoute: BalcaoRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  DashboardRoute: DashboardRoute,
  FinanceiroRoute: FinanceiroRoute,
  InsightsRoute: InsightsRoute,
  KitsRoute: KitsRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  ProdutosRoute: ProdutosRoute,
  ReportsRoute: ReportsRoute,
  ReposicaoRoute: ReposicaoRoute,
  SuppliersRoute: SuppliersRoute,
  VendasRoute: VendasRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
